In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv("road_accidents.csv")

In [3]:
df.head()

,TIME 24 HOURS,BASE/SUB BASE,COUNTY,ROAD,PLACE,MV INVOLVED,BRIEF ACCIDENT DETAILS,NAME OF VICTIM,GENDER,AGE,CAUSE CODE,VICTIM,NO.,Date DD/MM/YYYY,Unnamed: 14
0,630,KITUI,MAKUENI,KITUI-ITHOKWE,KITUI SCHOOL,KAV 479E & KMCZ 732L SKYGO,HEAD ON COLLISION,UNKNOWN,M,26,7,M/CYCLIST,1,06/25/16,so MM/DD/YYYY is the solution :)
1,830,VOI,TAITA TAVETA,MOMBASA-NAIROBI,IKANGA,KCC 763/ZF 0097 MAKE RENAULT TRUCK & KMDN 759R...,HEAD ON COLLISION,UNKNOWN,M,28,25,M/CYCLIST,1,06/25/16,NaN
2,1330,MARIAKANI,KILIFI,MOMBASA-NAIROBI,KATOLANI,KMDK 017U HAOJIN,THE UNKNOWN M/V HIT THE MOTOR CYCLE,UNKNOWN,M,A & J,98,M/CYCLIST,1,06/25/16,NaN
3,2100,ONGATA RONGAI,NAKURU,NAKURU-NAIROBI,MAASAI LODGE,KAL 900K RANGE ROVER,THE VEHICLE KNOCKED DOWN A PEDESTRIAN WHO WAS ...,UNKNOWN,M,65,29,PEDESTRIAN,1,06/25/16,NaN
4,1900,MATUU,MACHAKOS,MATUU-MWINGI,KIVANDINI,KAQ 865Z TOYOTA COROLLA,THE VEHICLE OVERTOOK A M/CYCLE AND LOST CONTRO...,UNKNOWN,M,A,10,PASSENGER,1,06/25/16,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1119 entries, 0 to 1118
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   TIME 24 HOURS           1114 non-null   str
 1   BASE/SUB BASE           1117 non-null   str
 2   COUNTY                  1116 non-null   str
 3   ROAD                    1116 non-null   str
 4   PLACE                   1113 non-null   str
 5   MV INVOLVED             1119 non-null   str
 6   BRIEF ACCIDENT DETAILS  1118 non-null   str
 7   NAME OF VICTIM          1118 non-null   str
 8   GENDER                  1119 non-null   str
 9   AGE                     1118 non-null   str
 10  CAUSE CODE              1091 non-null   str
 11  VICTIM                  1119 non-null   str
 12  NO.                     1115 non-null   str
 13  Date DD/MM/YYYY         1119 non-null   str
 14  Unnamed: 14             2 non-null      str
dtypes: str(15)
memory usage: 289.2 KB

In [5]:
df.shape

(1119, 15)

In [6]:
df.columns

Index(['TIME 24 HOURS', 'BASE/SUB BASE', 'COUNTY', 'ROAD', 'PLACE',
       'MV INVOLVED', 'BRIEF ACCIDENT DETAILS', 'NAME OF VICTIM', 'GENDER',
       'AGE', 'CAUSE CODE', 'VICTIM', 'NO.', 'Date DD/MM/YYYY', 'Unnamed: 14'],
      dtype='str')

In [7]:
df.isnull().sum()

TIME 24 HOURS                5
BASE/SUB BASE                2
COUNTY                       3
ROAD                         3
PLACE                        6
MV INVOLVED                  0
BRIEF ACCIDENT DETAILS       1
NAME OF VICTIM               1
GENDER                       0
AGE                          1
CAUSE CODE                  28
VICTIM                       0
NO.                          4
Date DD/MM/YYYY              0
Unnamed: 14               1117
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

# Rename the columns
The available columns are hard to work with.

In [9]:
df = df.rename(columns={
    "TIME 24 HOURS": "time",
    "BASE/SUB BASE": "base_sub_base",
    "COUNTY": "county",
    "ROAD": "road",
    "PLACE": "place",
    "MV INVOLVED": "vehicles_involved",
    "BRIEF ACCIDENT DETAILS": "accident_details",
    "NAME OF VICTIM": "victim_name",
    "GENDER": "gender",
    "AGE": "age",
    "CAUSE CODE": "cause_code",
    "VICTIM": "victim_type",
    "NO.": "number",
    "Date DD/MM/YYYY": "date",
    "Unnamed: 14": "unnamed_14"
})

In [10]:
df.columns

Index(['time', 'base_sub_base', 'county', 'road', 'place', 'vehicles_involved',
       'accident_details', 'victim_name', 'gender', 'age', 'cause_code',
       'victim_type', 'number', 'date', 'unnamed_14'],
      dtype='str')

In [11]:
df[df["time"] == "TIME 24 HOURS"]

,time,base_sub_base,county,road,place,vehicles_involved,accident_details,victim_name,gender,age,cause_code,victim_type,number,date,unnamed_14
378,TIME 24 HOURS,BASE/SUB BASE,COUNTY,ROAD,PLACE,MV INVOLVED,BRIEF ACCIDENT DETAILS,NAME OF VICTIM,GENDER,AGE,CAUSE CODE,VICTIM,NO.,Date DD/MM/YYYY,NaN

remove the copy

In [12]:
df = df[df["time"] != "TIME 24 HOURS"].copy()

In [13]:
df.shape

(1118, 15)

drop unnecessary column

In [14]:
df = df.drop(columns=["unnamed_14"])

drop victim names

In [15]:
df = df.drop(columns=["victim_name"])

In [16]:
df.shape

(1118, 13)

clean text column

In [17]:
text_columns = df.select_dtypes(include=["object", "string"]).columns

for column in text_columns:
    df[column] = df[column].astype("string").str.strip()

replace empty strings with proper missing values

In [18]:
df = df.replace("", np.nan)

In [20]:
df.isnull().sum()

time                  5
base_sub_base         2
county                3
road                  3
place                 6
vehicles_involved     0
accident_details      1
gender                0
age                   1
cause_code           28
victim_type           0
number                4
date                  0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df["county"].value_counts()

county
NAIROBI            183
KIAMBU              99
NAKURU              76
MAKUENI             60
MACHAKOS            50
KAKAMEGA            40
NYERI               38
KILIFI              32
KAJIADO             31
KISUMU              30
EMBU                29
MOMBASA             27
KERICHO             26
HOMA BAY            25
MERU                25
KISII               24
BUNGOMA             23
NAROK               21
KIRINYAGA           19
MURANGA             19
UASIN GISHU         17
BARINGO             16
NYANDARUA           16
NYAMIRA             15
KITUI               15
SIAYA               14
BOMET               14
TAITA TAVETA        13
MIGORI              13
GARISSA             12
BUSIA               11
KWALE               10
VIHIGA              10
NANDI                8
TRANS NZOIA          7
LAIKIPIA             6
MARSABIT             6
HOMABAY              5
MURANG'A             3
MWINGI               3
ELGEYO MARAKWET      3
WEST POKOT           3
THARAKA NITHI        2
ISIOLO               2
TAITA-TAVETA         2
KERCHO               1
MAKURU               1
NYAHURURU            1
MARAKWET             1
MALINDI              1
TIGANIA              1
MANDERA              1
KILFI                1
TRAN NZOIA           1
UASIN NGISHU         1
HOMA-BAY             1
MOYALE               1
Name: count, dtype: int64[pyarrow]

In [23]:
df["gender"].value_counts()

gender
M           941
F           142
M&F           8
M & F         5
J             4
F/J           2
M/J           2
M AND F       2
1             2
2M & 2F       1
2M, F         1
2F & M        1
2M & 3F       1
4F & INF      1
M&f           1
M/F           1
M & F/J       1
2M & F        1
M/A           1
Name: count, dtype: int64[pyarrow]

In [24]:
df["victim_type"].value_counts()

victim_type
PEDESTRIAN                       448
M/CYCLIST                        201
PASSENGER                        141
DRIVER                           115
P/PASSENGER                       75
P/CYCLIST                         22
RIDER                             21
PASSENGERS                        20
PEDAL CYCLIST                      6
DRIVER & PASSENGER                 6
RIDER & P/PASSENGER                6
M/CYLIST                           4
MOTOR CYCLIST                      3
M/CYCLIST & P/PASSENGER            3
PASSANGER                          3
7 PASSENGERS 1 DRIVER              2
DRIVER PASSENGER                   2
P/PASENGER                         2
P/PASSENGERS                       2
PEDSTIRAN                          2
DRIVER & 2 PASSENGERS              2
M/CYCLIST AND P/PASSENGER          2
2 PASSENGERS & DRIVER              1
2 PEDESTRIANS & PASSENGER          1
MOTOR CYCLIST & P/PASSENGER        1
4 PASSENGER 1 DRIVER               1
MOTOR CYCLIST P/PASSENGER          1
PASSEGER                           1
M/CYCLIT                           1
PILLION PASSENGER                  1
RIDER P/PASSANGER                  1
P/PEDESTRIAN                       1
DRIVER 2 PASSANGERS                1
PEDSTRIAN                          1
2 PASSENGERS & P/PASSENGER         1
2 DRIVER & 2 PASSENGER             1
PEDESTRAIN                         1
P/P/PASSENGER                      1
PEDESTRIANS                        1
PILLION PASSENGERS                 1
RE                                 1
M/ CYCLIST                         1
M/CYLIST & P/PASSENGER             1
DRIVER AND PASSENGER               1
PEDESTRIAN & RIDER                 1
RIDERS                             1
1 DRIVER & 2 PASSENGERS            1
1 DRIVER & 4 PASSENGERS            1
1 RIDER & 1P/PASSENGER             1
PASSENGER ,RIDER, P/PASSENGER      1
2 DRIVERS & PASSENGER              1
RIDER AND P/PASSENGER              1
Name: count, dtype: int64[pyarrow]

In [25]:
df["age"].value_counts().head(30)

age
A     545
30     38
40     35
J      26
25     23
28     22
35     20
26     18
33     16
32     16
60     14
36     13
45     13
27     12
19     11
23     11
31     11
20     10
42     10
38      9
50      9
37      8
12      8
70      7
29      6
57      6
55      6
48      6
43      6
39      6
Name: count, dtype: int64[pyarrow]

In [27]:
df["time"].value_counts().head(30)

time
2030    44
2100    39
2000    36
1900    29
1930    27
1800    25
1830    24
1730    24
2230    22
1630    21
2130    20
1600    20
700     19
1230    18
1100    18
2330    18
630     17
1700    17
2200    17
1330    16
1200    16
1030    16
730     16
1430    16
1500    15
930     14
1530    14
1000    14
1400    14
2300    14
Name: count, dtype: int64[pyarrow]

In [28]:
df.head()

,time,base_sub_base,county,road,place,vehicles_involved,accident_details,gender,age,cause_code,victim_type,number,date
0,630,KITUI,MAKUENI,KITUI-ITHOKWE,KITUI SCHOOL,KAV 479E & KMCZ 732L SKYGO,HEAD ON COLLISION,M,26,7,M/CYCLIST,1,06/25/16
1,830,VOI,TAITA TAVETA,MOMBASA-NAIROBI,IKANGA,KCC 763/ZF 0097 MAKE RENAULT TRUCK & KMDN 759R...,HEAD ON COLLISION,M,28,25,M/CYCLIST,1,06/25/16
2,1330,MARIAKANI,KILIFI,MOMBASA-NAIROBI,KATOLANI,KMDK 017U HAOJIN,THE UNKNOWN M/V HIT THE MOTOR CYCLE,M,A & J,98,M/CYCLIST,1,06/25/16
3,2100,ONGATA RONGAI,NAKURU,NAKURU-NAIROBI,MAASAI LODGE,KAL 900K RANGE ROVER,THE VEHICLE KNOCKED DOWN A PEDESTRIAN WHO WAS ...,M,65,29,PEDESTRIAN,1,06/25/16
4,1900,MATUU,MACHAKOS,MATUU-MWINGI,KIVANDINI,KAQ 865Z TOYOTA COROLLA,THE VEHICLE OVERTOOK A M/CYCLE AND LOST CONTRO...,M,A,10,PASSENGER,1,06/25/16

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 1118 entries, 0 to 1118
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   time               1113 non-null   string
 1   base_sub_base      1116 non-null   string
 2   county             1115 non-null   string
 3   road               1115 non-null   string
 4   place              1112 non-null   string
 5   vehicles_involved  1118 non-null   string
 6   accident_details   1117 non-null   string
 7   gender             1118 non-null   string
 8   age                1117 non-null   string
 9   cause_code         1090 non-null   string
 10  victim_type        1118 non-null   string
 11  number             1114 non-null   string
 12  date               1118 non-null   string
dtypes: string(13)
memory usage: 270.1 KB

## clean county values
keep the original county values before cleaning

In [30]:
df["county_raw"] = df["county"]

standardize capitalization and spaces

In [31]:
df["county"] = (
    df["county"]
    .astype("string")
    .str.upper()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [32]:
df["county"].value_counts()

county
NAIROBI            183
KIAMBU              99
NAKURU              76
MAKUENI             60
MACHAKOS            50
KAKAMEGA            40
NYERI               38
KILIFI              32
KAJIADO             31
KISUMU              30
EMBU                29
MOMBASA             27
KERICHO             26
HOMA BAY            25
MERU                25
KISII               24
BUNGOMA             23
NAROK               21
KIRINYAGA           19
MURANGA             19
UASIN GISHU         17
BARINGO             16
NYANDARUA           16
NYAMIRA             15
KITUI               15
SIAYA               14
BOMET               14
TAITA TAVETA        13
MIGORI              13
GARISSA             12
BUSIA               11
KWALE               10
VIHIGA              10
NANDI                8
TRANS NZOIA          7
LAIKIPIA             6
MARSABIT             6
HOMABAY              5
MURANG'A             3
MWINGI               3
ELGEYO MARAKWET      3
WEST POKOT           3
THARAKA NITHI        2
ISIOLO               2
TAITA-TAVETA         2
KERCHO               1
MAKURU               1
NYAHURURU            1
MARAKWET             1
MALINDI              1
TIGANIA              1
MANDERA              1
KILFI                1
TRAN NZOIA           1
UASIN NGISHU         1
HOMA-BAY             1
MOYALE               1
Name: count, dtype: int64[pyarrow]

Correct spelling and naming inconsistencies

In [41]:
county_corrections = {
    "HOMABAY": "HOMA BAY",
    "HOMA-BAY": "HOMA BAY",
    
    "MURANGA": "MURANG'A",
    
    "TAITA-TAVETA": "TAITA TAVETA",
    
    "KERCHO": "KERICHO",
    "KILFI": "KILIFI",
    
    "TRAN NZOIA": "TRANS NZOIA",
    "UASIN NGISHU": "UASIN GISHU",
    
    "MAKURU": "NAKURU",
    
    "MARAKWET": "ELGEYO MARAKWET",
    
    "NYAHURURU": "LAIKIPIA",
    "MWINGI": "KITUI",
    "TIGANIA": "MERU",
    "MALINDI": "KILIFI",
    "MOYALE": "MARSABIT"
}

df["county"] = df["county"].replace(county_corrections)

check missing counties

In [42]:
df[df["county"].isna()][
    ["time", "base_sub_base", "road", "place"]
]

Empty DataFrame
Columns: [time, base_sub_base, road, place]
Index: []

nanyuki entry belongs to laikipia, kinangop to nyandarua and mwangulu to kwale

In [43]:
df.loc[
    df["county"].isna() &
    (df["base_sub_base"] == "NANYUKI"),
    "county"
] = "LAIKIPIA"

In [44]:
df.loc[
    df["county"].isna() &
    (df["base_sub_base"] == "KINANGOP"),
    "county"
] = "NYANDARUA"

In [45]:
df.loc[
    df["county"].isna() &
    df["road"].str.contains("MWANGULU", case=False, na=False),
    "county"
] = "KWALE"

In [46]:
df["county"].isnull().sum()

np.int64(0)

In [47]:
df["county"].nunique()

42

inspect cleaned counties

In [48]:
sorted(df["county"].unique())

['BARINGO',
 'BOMET',
 'BUNGOMA',
 'BUSIA',
 'ELGEYO MARAKWET',
 'EMBU',
 'GARISSA',
 'HOMA BAY',
 'ISIOLO',
 'KAJIADO',
 'KAKAMEGA',
 'KERICHO',
 'KIAMBU',
 'KILIFI',
 'KIRINYAGA',
 'KISII',
 'KISUMU',
 'KITUI',
 'KWALE',
 'LAIKIPIA',
 'MACHAKOS',
 'MAKUENI',
 'MANDERA',
 'MARSABIT',
 'MERU',
 'MIGORI',
 'MOMBASA',
 "MURANG'A",
 'NAIROBI',
 'NAKURU',
 'NANDI',
 'NAROK',
 'NYAMIRA',
 'NYANDARUA',
 'NYERI',
 'SIAYA',
 'TAITA TAVETA',
 'THARAKA NITHI',
 'TRANS NZOIA',
 'UASIN GISHU',
 'VIHIGA',
 'WEST POKOT']

In [49]:
df["county"].value_counts()

county
NAIROBI            183
KIAMBU              99
NAKURU              77
MAKUENI             60
MACHAKOS            50
KAKAMEGA            40
NYERI               38
KILIFI              34
HOMA BAY            31
KAJIADO             31
KISUMU              30
EMBU                29
MOMBASA             27
KERICHO             27
MERU                26
KISII               24
BUNGOMA             23
MURANG'A            22
NAROK               21
KIRINYAGA           19
UASIN GISHU         18
KITUI               18
NYANDARUA           17
BARINGO             16
TAITA TAVETA        15
NYAMIRA             15
SIAYA               14
BOMET               14
MIGORI              13
GARISSA             12
KWALE               11
BUSIA               11
VIHIGA              10
NANDI                8
TRANS NZOIA          8
LAIKIPIA             8
MARSABIT             7
ELGEYO MARAKWET      4
WEST POKOT           3
THARAKA NITHI        2
ISIOLO               2
MANDERA              1
Name: count, dtype: int64[pyarrow]

compare before and after

In [50]:
print("Unique county values before cleaning:",
      df["county_raw"].nunique())

print("Unique counties after cleaning:",
      df["county"].nunique())

print("Missing counties after cleaning:",
      df["county"].isnull().sum())

Unique county values before cleaning: 57
Unique counties after cleaning: 42
Missing counties after cleaning: 0

## clean gender values

In [51]:
df["gender_raw"] = df["gender"]

In [52]:
df["gender"].value_counts(dropna=False)

gender
M           941
F           142
M&F           8
M & F         5
J             4
F/J           2
M/J           2
M AND F       2
1             2
2M & 2F       1
2M, F         1
2F & M        1
2M & 3F       1
4F & INF      1
M&f           1
M/F           1
M & F/J       1
2M & F        1
M/A           1
Name: count, dtype: int64[pyarrow]

create a gender mapping

In [53]:
gender_mapping = {
    "M": "MALE",
    "F": "FEMALE",

    "M&F": "MIXED",
    "M & F": "MIXED",
    "M AND F": "MIXED",
    "M&f": "MIXED",
    "M/F": "MIXED",

    "2M & 3F": "MIXED",
    "2M & 2F": "MIXED",
    "2M, F": "MIXED",
    "2F & M": "MIXED",
    "2M & F": "MIXED",
    "M & F/J": "MIXED",
    "4F & INF": "MIXED",

    "M/J": "MALE",
    "M/A": "MALE",
    "F/J": "FEMALE",

    "J": "UNKNOWN",
    "1": "UNKNOWN"
}

In [54]:
df["gender"] = df["gender"].replace(gender_mapping)

In [55]:
df["gender"].value_counts()

gender
MALE       944
FEMALE     144
MIXED       24
UNKNOWN      6
Name: count, dtype: int64[pyarrow]

## clean victim type

preserve original

In [56]:
df["victim_type_raw"] = df["victim_type"]

In [57]:
df["victim_type"].value_counts()

victim_type
PEDESTRIAN                       448
M/CYCLIST                        201
PASSENGER                        141
DRIVER                           115
P/PASSENGER                       75
P/CYCLIST                         22
RIDER                             21
PASSENGERS                        20
PEDAL CYCLIST                      6
DRIVER & PASSENGER                 6
RIDER & P/PASSENGER                6
M/CYLIST                           4
MOTOR CYCLIST                      3
M/CYCLIST & P/PASSENGER            3
PASSANGER                          3
7 PASSENGERS 1 DRIVER              2
DRIVER PASSENGER                   2
P/PASENGER                         2
P/PASSENGERS                       2
PEDSTIRAN                          2
DRIVER & 2 PASSENGERS              2
M/CYCLIST AND P/PASSENGER          2
2 PASSENGERS & DRIVER              1
2 PEDESTRIANS & PASSENGER          1
MOTOR CYCLIST & P/PASSENGER        1
4 PASSENGER 1 DRIVER               1
MOTOR CYCLIST P/PASSENGER          1
PASSEGER                           1
M/CYCLIT                           1
PILLION PASSENGER                  1
RIDER P/PASSANGER                  1
P/PEDESTRIAN                       1
DRIVER 2 PASSANGERS                1
PEDSTRIAN                          1
2 PASSENGERS & P/PASSENGER         1
2 DRIVER & 2 PASSENGER             1
PEDESTRAIN                         1
P/P/PASSENGER                      1
PEDESTRIANS                        1
PILLION PASSENGERS                 1
RE                                 1
M/ CYCLIST                         1
M/CYLIST & P/PASSENGER             1
DRIVER AND PASSENGER               1
PEDESTRIAN & RIDER                 1
RIDERS                             1
1 DRIVER & 2 PASSENGERS            1
1 DRIVER & 4 PASSENGERS            1
1 RIDER & 1P/PASSENGER             1
PASSENGER ,RIDER, P/PASSENGER      1
2 DRIVERS & PASSENGER              1
RIDER AND P/PASSENGER              1
Name: count, dtype: int64[pyarrow]

victim type corrections

In [58]:
victim_mapping = {

    # Passenger
    "PASSENGERS": "PASSENGER",
    "PASSANGER": "PASSENGER",
    "PASSEGER": "PASSENGER",

    # Pedestrian
    "PEDSTIRAN": "PEDESTRIAN",
    "PEDSTRIAN": "PEDESTRIAN",
    "PEDESTRAIN": "PEDESTRIAN",
    "PEDESTRIANS": "PEDESTRIAN",
    "P/PEDESTRIAN": "PEDESTRIAN",

    # Motorcyclist
    "M/CYCLIST": "MOTORCYCLIST",
    "M/CYLIST": "MOTORCYCLIST",
    "M/CYCLIT": "MOTORCYCLIST",
    "M/ CYCLIST": "MOTORCYCLIST",
    "MOTOR CYCLIST": "MOTORCYCLIST",

    # Pedal cyclist
    "P/CYCLIST": "PEDAL CYCLIST",

    # Pillion passenger
    "P/PASSENGER": "PILLION PASSENGER",
    "P/PASENGER": "PILLION PASSENGER",
    "P/PASSENGERS": "PILLION PASSENGER",
    "P/P/PASSENGER": "PILLION PASSENGER",
    "PILLION PASSENGERS": "PILLION PASSENGER",

    # Rider
    "RIDERS": "RIDER",

    # Driver and passenger
    "DRIVER PASSENGER": "DRIVER & PASSENGER",
    "DRIVER AND PASSENGER": "DRIVER & PASSENGER",
    "DRIVER & 2 PASSENGERS": "DRIVER & PASSENGER",
    "7 PASSENGERS 1 DRIVER": "DRIVER & PASSENGER",
    "2 PASSENGERS & DRIVER": "DRIVER & PASSENGER",
    "4 PASSENGER 1 DRIVER": "DRIVER & PASSENGER",
    "DRIVER 2 PASSANGERS": "DRIVER & PASSENGER",
    "2 DRIVER & 2 PASSENGER": "DRIVER & PASSENGER",
    "1 DRIVER & 2 PASSENGERS": "DRIVER & PASSENGER",
    "1 DRIVER & 4 PASSENGERS": "DRIVER & PASSENGER",
    "2 DRIVERS & PASSENGER": "DRIVER & PASSENGER",

    # Rider and pillion passenger
    "RIDER & P/PASSENGER": "RIDER & PILLION PASSENGER",
    "RIDER P/PASSANGER": "RIDER & PILLION PASSENGER",
    "RIDER AND P/PASSENGER": "RIDER & PILLION PASSENGER",
    "1 RIDER & 1P/PASSENGER": "RIDER & PILLION PASSENGER",

    # Motorcyclist and pillion passenger
    "M/CYCLIST & P/PASSENGER": "MOTORCYCLIST & PILLION PASSENGER",
    "M/CYCLIST AND P/PASSENGER": "MOTORCYCLIST & PILLION PASSENGER",
    "MOTOR CYCLIST P/PASSENGER": "MOTORCYCLIST & PILLION PASSENGER",
    "MOTOR CYCLIST & P/PASSENGER": "MOTORCYCLIST & PILLION PASSENGER",
    "M/CYLIST & P/PASSENGER": "MOTORCYCLIST & PILLION PASSENGER",

    # Other combinations
    "2 PEDESTRIANS & PASSENGER": "PEDESTRIAN & PASSENGER",
    "2 PASSENGERS & P/PASSENGER": "PASSENGER & PILLION PASSENGER",
    "PASSENGER ,RIDER, P/PASSENGER":
        "PASSENGER & RIDER & PILLION PASSENGER"
}

apply it

In [59]:
df["victim_type"] = df["victim_type"].replace(victim_mapping)

In [60]:
df["victim_type"] = df["victim_type"].replace({
    "RE": "UNKNOWN"
})

In [63]:
df["victim_type"].value_counts()

victim_type
PEDESTRIAN                               454
MOTORCYCLIST                             210
PASSENGER                                165
DRIVER                                   115
PILLION PASSENGER                         82
PEDAL CYCLIST                             28
RIDER                                     22
DRIVER & PASSENGER                        20
RIDER & PILLION PASSENGER                  9
MOTORCYCLIST & PILLION PASSENGER           8
PEDESTRIAN & PASSENGER                     1
PASSENGER & PILLION PASSENGER              1
UNKNOWN                                    1
PEDESTRIAN & RIDER                         1
PASSENGER & RIDER & PILLION PASSENGER      1
Name: count, dtype: int64[pyarrow]

compare before and after

In [64]:
print("Original gender categories:",
      df["gender_raw"].nunique())

print("Cleaned gender categories:",
      df["gender"].nunique())

print()

print("Original victim type categories:",
      df["victim_type_raw"].nunique())

print("Cleaned victim type categories:",
      df["victim_type"].nunique())

Original gender categories: 19
Cleaned gender categories: 4

Original victim type categories: 52
Cleaned victim type categories: 15

In [65]:
df[[
    "gender_raw",
    "gender",
    "victim_type_raw",
    "victim_type"
]].head(20)

   gender_raw  gender            victim_type_raw             victim_type
0           M    MALE                  M/CYCLIST            MOTORCYCLIST
1           M    MALE                  M/CYCLIST            MOTORCYCLIST
2           M    MALE                  M/CYCLIST            MOTORCYCLIST
3           M    MALE                 PEDESTRIAN              PEDESTRIAN
4           M    MALE                  PASSENGER               PASSENGER
5           M    MALE                 PEDESTRIAN              PEDESTRIAN
6       M & F   MIXED      2 PASSENGERS & DRIVER      DRIVER & PASSENGER
7           M    MALE                  M/CYCLIST            MOTORCYCLIST
8           F  FEMALE                 PEDESTRIAN              PEDESTRIAN
9           M    MALE                P/PASSENGER       PILLION PASSENGER
10          F  FEMALE  2 PEDESTRIANS & PASSENGER  PEDESTRIAN & PASSENGER
11          M    MALE                  M/CYCLIST            MOTORCYCLIST
12          M    MALE                 PEDESTRIAN              PEDESTRIAN
13          M    MALE                  M/CYCLIST            MOTORCYCLIST
14          M    MALE                  M/CYCLIST            MOTORCYCLIST
15          F  FEMALE                 PEDESTRIAN              PEDESTRIAN
16          M    MALE                  M/CYCLIST            MOTORCYCLIST
17          M    MALE                  M/CYCLIST            MOTORCYCLIST
18          M    MALE                 PEDESTRIAN              PEDESTRIAN
19          M    MALE                  M/CYCLIST            MOTORCYCLIST

In [67]:
df.head()

,time,base_sub_base,county,road,place,vehicles_involved,accident_details,gender,age,cause_code,victim_type,number,date,county_raw,gender_raw,victim_type_raw
0,630,KITUI,MAKUENI,KITUI-ITHOKWE,KITUI SCHOOL,KAV 479E & KMCZ 732L SKYGO,HEAD ON COLLISION,MALE,26,7,MOTORCYCLIST,1,06/25/16,MAKUENI,M,M/CYCLIST
1,830,VOI,TAITA TAVETA,MOMBASA-NAIROBI,IKANGA,KCC 763/ZF 0097 MAKE RENAULT TRUCK & KMDN 759R...,HEAD ON COLLISION,MALE,28,25,MOTORCYCLIST,1,06/25/16,TAITA TAVETA,M,M/CYCLIST
2,1330,MARIAKANI,KILIFI,MOMBASA-NAIROBI,KATOLANI,KMDK 017U HAOJIN,THE UNKNOWN M/V HIT THE MOTOR CYCLE,MALE,A & J,98,MOTORCYCLIST,1,06/25/16,KILIFI,M,M/CYCLIST
3,2100,ONGATA RONGAI,NAKURU,NAKURU-NAIROBI,MAASAI LODGE,KAL 900K RANGE ROVER,THE VEHICLE KNOCKED DOWN A PEDESTRIAN WHO WAS ...,MALE,65,29,PEDESTRIAN,1,06/25/16,NAKURU,M,PEDESTRIAN
4,1900,MATUU,MACHAKOS,MATUU-MWINGI,KIVANDINI,KAQ 865Z TOYOTA COROLLA,THE VEHICLE OVERTOOK A M/CYCLE AND LOST CONTRO...,MALE,A,10,PASSENGER,1,06/25/16,MACHAKOS,M,PASSENGER

In [68]:
df["age_raw"] = df["age"]

create numeric age column

In [69]:
df["age_numeric"] = pd.to_numeric(df["age"], errors="coerce")

create an age category column that keeps the meaning of A and J

In [70]:
def clean_age_category(value):
    value = str(value).strip().upper()

    if value == "A":
        return "ADULT"
    elif value == "J":
        return "JUVENILE"
    elif "A" in value and "J" in value:
        return "ADULT & JUVENILE"
    elif value.isdigit():
        return "NUMERIC AGE"
    else:
        return "UNKNOWN"

df["age_category"] = df["age"].apply(clean_age_category)

In [71]:
df["age_category"].value_counts()

age_category
ADULT               545
NUMERIC AGE         510
UNKNOWN              31
JUVENILE             26
ADULT & JUVENILE      6
Name: count, dtype: int64

for the rows with actual ages, create proper age groups:

In [73]:
bins = [0, 17, 24, 34, 44, 54, 64, np.inf]

labels = [
    "0-17",
    "18-24",
    "25-34",
    "35-44",
    "45-54",
    "55-64",
    "65+"
]

df["age_group"] = pd.cut(
    df["age_numeric"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

## clean the date column

In [74]:
df["date_raw"] = df["date"]

In [75]:
def clean_date(row):
    value = str(row["date"]).strip()
    parts = value.split("/")

    try:
        # Example: 6/24
        if len(parts) == 2:
            month, day = map(int, parts)

            # First section of dataset = 2016
            # Second section = 2017
            year = 2016 if row.name < 379 else 2017

        # Example: 06/25/16 or 10/31/2017
        elif len(parts) == 3:
            month = int(parts[0])
            day = int(parts[1])
            year = int(parts[2])

            if year < 100:
                year += 2000

        else:
            return pd.NaT

        return pd.Timestamp(
            year=year,
            month=month,
            day=day
        )

    except:
        return pd.NaT

In [76]:
df["date"] = df.apply(clean_date, axis=1)

In [77]:
df[["date_raw", "date"]].head(20)

    date_raw       date
0   06/25/16 2016-06-25
1   06/25/16 2016-06-25
2   06/25/16 2016-06-25
3   06/25/16 2016-06-25
4   06/25/16 2016-06-25
5   06/25/16 2016-06-25
6   06/25/16 2016-06-25
7       6/24 2016-06-24
8       6/24 2016-06-24
9       6/24 2016-06-24
10      6/24 2016-06-24
11      6/24 2016-06-24
12      6/24 2016-06-24
13      6/24 2016-06-24
14   6/23/16 2016-06-23
15   6/23/16 2016-06-23
16   6/23/16 2016-06-23
17   6/23/16 2016-06-23
18   6/23/16 2016-06-23
19   6/23/16 2016-06-23

In [78]:
df["date"].isnull().sum()

np.int64(0)

create useful date variables

In [79]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["month_name"] = df["date"].dt.month_name()
df["day"] = df["date"].dt.day
df["day_name"] = df["date"].dt.day_name()

In [80]:
df[
    ["date", "year", "month", "month_name", "day", "day_name"]
].head()

        date  year  month month_name  day  day_name
0 2016-06-25  2016      6       June   25  Saturday
1 2016-06-25  2016      6       June   25  Saturday
2 2016-06-25  2016      6       June   25  Saturday
3 2016-06-25  2016      6       June   25  Saturday
4 2016-06-25  2016      6       June   25  Saturday

## clean time column

In [81]:
df["time_raw"] = df["time"]

In [82]:
time_clean = (
    df["time"]
    .astype("string")
    .str.upper()
    .str.strip()
    .str.replace("HRS", "", regex=False)
    .str.strip()
)

replace invalid values

In [83]:
time_clean = time_clean.replace({
    "UNKNOWN": pd.NA,
    "UNKNOWN TIME": pd.NA,
    "NAROK": pd.NA
})

In [84]:
time_clean = time_clean.str.zfill(4)

In [85]:
time_clean.head(20)

0     0630
1     0830
2     1330
3     2100
4     1900
5     2130
6     1200
7     1330
8     1930
9     2030
10    1900
11    2130
12    0040
13    0300
14    1150
15    0330
16    1700
17    2130
18    2130
19    2100
Name: time, dtype: string

extract hour and minute

In [86]:
df["hour"] = pd.to_numeric(
    time_clean.str[:2],
    errors="coerce"
)

df["minute"] = pd.to_numeric(
    time_clean.str[2:],
    errors="coerce"
)

In [87]:
df[["time_raw", "hour", "minute"]].head(20)

   time_raw  hour  minute
0       630     6      30
1       830     8      30
2      1330    13      30
3      2100    21       0
4      1900    19       0
5      2130    21      30
6      1200    12       0
7      1330    13      30
8      1930    19      30
9      2030    20      30
10     1900    19       0
11     2130    21      30
12       40     0      40
13      300     3       0
14     1150    11      50
15      330     3      30
16     1700    17       0
17     2130    21      30
18     2130    21      30
19     2100    21       0

## create time of day category

In [88]:
def time_period(hour):
    if pd.isna(hour):
        return "UNKNOWN"
    elif 5 <= hour < 12:
        return "MORNING"
    elif 12 <= hour < 17:
        return "AFTERNOON"
    elif 17 <= hour < 21:
        return "EVENING"
    else:
        return "NIGHT"

In [89]:
df["time_period"] = df["hour"].apply(time_period)

In [90]:
df["time_period"].value_counts()

time_period
EVENING      341
NIGHT        279
MORNING      244
AFTERNOON    231
UNKNOWN       23
Name: count, dtype: int64

## clean cause code

In [91]:
df["cause_code_raw"] = df["cause_code"]

convert to numeric

In [92]:
df["cause_code"] = pd.to_numeric(
    df["cause_code"],
    errors="coerce"
).astype("Int64")

create broader groups

In [96]:
def cause_group(code):

    if pd.isna(code):
        return "NOT RECORDED"

    elif 1 <= code <= 58:
        return "DRIVER / CYCLIST BEHAVIOUR"

    elif 59 <= code <= 68:
        return "PEDESTRIAN BEHAVIOUR"

    elif 69 <= code <= 73:
        return "PASSENGER / ATTENDANT"

    elif 74 <= code <= 75:
        return "ANIMAL"

    elif 76 <= code <= 77:
        return "OBSTRUCTION"

    elif 78 <= code <= 89:
        return "VEHICLE DEFECT"

    elif 90 <= code <= 93:
        return "ROAD CONDITION"

    elif 94 <= code <= 96:
        return "WEATHER"

    else:
        return "CAUSE NOT TRACED"

In [97]:
df["cause_group"] = df["cause_code"].apply(cause_group)

In [98]:
df["cause_group"].value_counts()

cause_group
DRIVER / CYCLIST BEHAVIOUR    623
CAUSE NOT TRACED              226
PEDESTRIAN BEHAVIOUR          163
VEHICLE DEFECT                 41
PASSENGER / ATTENDANT          28
NOT RECORDED                   28
ROAD CONDITION                  5
OBSTRUCTION                     4
Name: count, dtype: int64

## clean vehicle type

In [99]:
df["vehicles_involved_raw"] = df["vehicles_involved"]

standardize

In [100]:
df["vehicles_involved"] = (
    df["vehicles_involved"]
    .astype("string")
    .str.upper()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [101]:
df["vehicles_involved"].value_counts().head(20)

vehicles_involved
UNKNOWN                                              54
UNKNOWN M/V                                          45
UNKNOWN M/V (HIT AND RUN)                             4
UNKNOWN M/V AND M/A/PED                               3
KBW 777C TOYOTA PRADO & KMDE 953N TORNADO             2
KCE 161S ISUZU LORRY                                  2
KBZ 710R T/AVENSIS                                    2
KCD 078M/ZD 9607 SHACKMAN                             2
KCE 051E T/PROBOX & MITSUBISHI PETROL TANKER          2
UNKNOWN M/V & KMDR 603A BOXER                         2
UNKNOWN M/V & M/J/PED                                 2
KAV 219P TOYOTA PRADO KMDU 305L BAJAJ BOXER           2
KBX 432Z TOYOTA MATATU                                2
KBC 577Y MITS LORRY AND KCA 407Y TOYOTA L/CRUISER     2
KBZ 485A TOYOTA ISIS KMCG 028P TVS                    2
KCE 925S TOYOTA MATATU & KMDV 042G TVS STAR           2
KBT 349D TOYOTA CROWN & KAP 945X TOYOTA G TOURING     2
KCC 193Q TOYOTA PROBOX & KBQ 127H TOYOTA TOWNACE      2
KBJ 603D MITSUBISH LORRY & KAS 427M T/MATATU          2
KBX 076S HINO BUS & KBX 859P TOYOTA SURF              2
Name: count, dtype: int64[pyarrow]

Create broad vehicle-type flags

In [102]:
df["motorcycle"] = df["vehicles_involved"].str.contains(
    r"M/?CYCLE|MOTOR\s*CYCLE|M/C\b|BOXER|TVS|BAJAJ|SKYGO|DAYUN|HAOJIN|YAMAHA",
    case=False,
    regex=True,
    na=False
)

In [103]:
df["matatu"] = df["vehicles_involved"].str.contains(
    r"MATATU",
    case=False,
    regex=True,
    na=False
)

In [104]:
df["bus"] = df["vehicles_involved"].str.contains(
    r"\bBUS\b",
    case=False,
    regex=True,
    na=False
)

In [105]:
df["lorry_truck"] = df["vehicles_involved"].str.contains(
    r"LORRY|LORRIES|TRUCK|CANTER|PRIME MOVER|ACTROS|TIPPER|SHACKMAN|SHACMAN|DAF|FUSO",
    case=False,
    regex=True,
    na=False
)

In [106]:
df["pickup"] = df["vehicles_involved"].str.contains(
    r"P/?UP|PICK[\s-]?UP|HILUX",
    case=False,
    regex=True,
    na=False
)

In [107]:
df["tractor"] = df["vehicles_involved"].str.contains(
    r"\bTRACTOR\b",
    case=False,
    regex=True,
    na=False
)

In [111]:
df["trailer_tanker"] = df["vehicles_involved"].str.contains(
    r"TRAILER|TANKER",
    case=False,
    regex=True,
    na=False
)

In [108]:
df["car_suv"] = df["vehicles_involved"].str.contains(
    r"SALOON|PROBOX|PRADO|FIELDER|COROLLA|PREMIO|"
    r"AVENSIS|WISH|XTRAIL|X-TRAIL|HARRIER|BELTA|"
    r"LAND CRUISER|L/CRUISER|SURF|SIENTA|VITZ|RAV4|"
    r"ISIS|CROWN",
    case=False,
    regex=True,
    na=False
)

In [109]:
df["unknown_vehicle"] = df["vehicles_involved"].str.contains(
    r"UNKNOWN",
    case=False,
    regex=True,
    na=False
)

In [112]:
vehicle_counts = pd.Series({
    "Motorcycle": df["motorcycle"].sum(),
    "Car / SUV": df["car_suv"].sum(),
    "Lorry / Truck": df["lorry_truck"].sum(),
    "Matatu": df["matatu"].sum(),
    "Bus": df["bus"].sum(),
    "Trailer / Tanker": df["trailer_tanker"].sum(),
    "Pickup": df["pickup"].sum(),
    "Tractor": df["tractor"].sum(),
    "Unknown Vehicle": df["unknown_vehicle"].sum()
})

vehicle_counts.sort_values(ascending=False)

Motorcycle          232
Car / SUV           217
Lorry / Truck       187
Unknown Vehicle     150
Matatu              135
Bus                  98
Trailer / Tanker     64
Pickup               35
Tractor              12
dtype: int64

identify records we havent classified

In [113]:
vehicle_flag_columns = [
    "motorcycle",
    "car_suv",
    "lorry_truck",
    "matatu",
    "bus",
    "trailer_tanker",
    "pickup",
    "tractor",
    "unknown_vehicle"
]

df["vehicle_classified"] = df[vehicle_flag_columns].any(axis=1)

In [114]:
df["vehicle_classified"].value_counts()

vehicle_classified
True     905
False    213
Name: count, dtype: Int64

In [115]:
df.loc[
    ~df["vehicle_classified"],
    "vehicles_involved"
].value_counts().head(30)

vehicles_involved
KBS 468J & KMDQ 328H                        2
KMCL 800W                                   2
KAL 900K RANGE ROVER                        1
KCC 742P TOYOTA VAN                         1
KAG 069M PEGEOT 405                         1
KAZ 006V MITSUBISHI                         1
KAW 366A TOWNACE                            1
KAR 635G TOYOTA G TOURING                   1
KBT 945N                                    1
KCA 638W TOYOTA SUCEED                      1
KBL 381F ZD 6164                            1
KMCD 333C KMCY 801M                         1
KCF 664D/ZD 3111 & KMDD 552P                1
KCE 343P                                    1
KBZ 571 T/MARK X                            1
KAT 408K PAJERO & KAD 018F                  1
KBP 778W T/MARK II                          1
KCF 753C T/PASSO & KTWA 398C                1
KAS 215P T/HIACE                            1
KBR 302N/ZE 0353                            1
KAQ 572T G/TOURING                          1
KAW 594U TOYOTA DX                          1
KBT 699A TOYOTA ALLION                      1
KCC 415P TOYOTA                             1
KCE 487L TOYOTA SUCCED                      1
KBY 871C FORD EVEREST                       1
KBC 549K TOYOTA NOAH                        1
KBP 507E T/HILLUX & KBD 331W NEW HOLLAND    1
KBZ 742W T/RUSH & M/J/PED                   1
M/V KAX 550X & F/J/PED                      1
Name: count, dtype: int64[pyarrow]

Expand the Car / SUV category

In [116]:
df["car_suv"] = df["car_suv"] | df["vehicles_involved"].str.contains(
    r"RANGE ROVER|PEGEOT|PEUGEOT|MARK X|MARK II|PASSO|"
    r"PAJERO|ALLION|SUCCEED|SUC[E]?ED|EVEREST|RUSH|"
    r"G TOURING|TOYOTA DX",
    case=False,
    regex=True,
    na=False
)

In [117]:
df["van_minivan"] = df["vehicles_involved"].str.contains(
    r"\bVAN\b|TOWNACE|HIACE|NOAH",
    case=False,
    regex=True,
    na=False
)

In [118]:
df["pickup"] = df["pickup"] | df["vehicles_involved"].str.contains(
    r"HILUX|HILLUX|PICK[\s-]?UP|P/?UP",
    case=False,
    regex=True,
    na=False
)

In [119]:
df["tractor"] = df["tractor"] | df["vehicles_involved"].str.contains(
    r"TRACTOR|NEW HOLLAND",
    case=False,
    regex=True,
    na=False
)

In [120]:
vehicle_flag_columns = [
    "motorcycle",
    "car_suv",
    "van_minivan",
    "lorry_truck",
    "matatu",
    "bus",
    "trailer_tanker",
    "pickup",
    "tractor",
    "unknown_vehicle"
]

In [121]:
df["vehicle_classified"] = df[vehicle_flag_columns].any(axis=1)

In [122]:
df.loc[
    ~df["vehicle_classified"],
    "vehicles_involved"
].value_counts().head(30)

vehicles_involved
KBS 468J & KMDQ 328H                                  2
KMCL 800W                                             2
KAZ 006V MITSUBISHI                                   1
KBT 945N                                              1
KBL 381F ZD 6164                                      1
KMCD 333C KMCY 801M                                   1
KCF 664D/ZD 3111 & KMDD 552P                          1
KCE 343P                                              1
KBR 302N/ZE 0353                                      1
KAQ 572T G/TOURING                                    1
KCC 415P TOYOTA                                       1
KCE 487L TOYOTA SUCCED                                1
M/V KAX 550X & F/J/PED                                1
KBH 402H TOYOTA CALDINA                               1
KMCS 018V SOREHYI                                     1
KCE 849E NISSAN NOTE                                  1
KBM 162K ASHOK LEYLAND                                1
KMDK 671L SUZUKI AND KMDC 749S KAWASAKI               1
GKB 098J TOYOTA LANDCRUISER                           1
KCC 387Z/ZE 2857Z M/BENZ & KBQ 664P/ZC 3621 M/BENZ    1
T42DFR ROSA & KMDL 703P SHINALI                       1
KBJ 786V TOYOTA S/WAGEN                               1
KAT 188T TOYOTA RAV 4                                 1
KMDK 768A FOCIN                                       1
KAC 711Q NISSAN SUNNY                                 1
KMDT 713Y CAPTAIN                                     1
KBA 195Z TOYOTA RAUM                                  1
KBY 994J/ZE 6869 M/BENZ ACROS & KBX 285K ISUZU SR.    1
KBV 033Q MITSUBISHI FH                                1
KMDV 176D HONDA                                       1
Name: count, dtype: int64[pyarrow]

In [123]:
df["unspecified_vehicle"] = ~df["vehicle_classified"]

In [124]:
vehicle_counts = pd.Series({
    "Motorcycle": df["motorcycle"].sum(),
    "Car / SUV": df["car_suv"].sum(),
    "Van / Minivan": df["van_minivan"].sum(),
    "Lorry / Truck": df["lorry_truck"].sum(),
    "Matatu": df["matatu"].sum(),
    "Bus": df["bus"].sum(),
    "Trailer / Tanker": df["trailer_tanker"].sum(),
    "Pickup": df["pickup"].sum(),
    "Tractor": df["tractor"].sum(),
    "Unknown Vehicle": df["unknown_vehicle"].sum(),
    "Unspecified Type": df["unspecified_vehicle"].sum()
})

vehicle_counts.sort_values(ascending=False)

Car / SUV           247
Motorcycle          232
Lorry / Truck       187
Unspecified Type    161
Unknown Vehicle     150
Matatu              135
Bus                  98
Trailer / Tanker     64
Pickup               38
Van / Minivan        35
Tractor              17
dtype: int64

In [125]:
df.head()

,time,base_sub_base,county,road,place,vehicles_involved,accident_details,gender,age,cause_code,...,bus,lorry_truck,pickup,tractor,car_suv,unknown_vehicle,trailer_tanker,vehicle_classified,van_minivan,unspecified_vehicle
0,630,KITUI,MAKUENI,KITUI-ITHOKWE,KITUI SCHOOL,KAV 479E & KMCZ 732L SKYGO,HEAD ON COLLISION,MALE,26,7,...,False,False,False,False,False,False,False,True,False,False
1,830,VOI,TAITA TAVETA,MOMBASA-NAIROBI,IKANGA,KCC 763/ZF 0097 MAKE RENAULT TRUCK & KMDN 759R...,HEAD ON COLLISION,MALE,28,25,...,False,True,False,False,False,False,False,True,False,False
2,1330,MARIAKANI,KILIFI,MOMBASA-NAIROBI,KATOLANI,KMDK 017U HAOJIN,THE UNKNOWN M/V HIT THE MOTOR CYCLE,MALE,A & J,98,...,False,False,False,False,False,False,False,True,False,False
3,2100,ONGATA RONGAI,NAKURU,NAKURU-NAIROBI,MAASAI LODGE,KAL 900K RANGE ROVER,THE VEHICLE KNOCKED DOWN A PEDESTRIAN WHO WAS ...,MALE,65,29,...,False,False,False,False,True,False,False,True,False,False
4,1900,MATUU,MACHAKOS,MATUU-MWINGI,KIVANDINI,KAQ 865Z TOYOTA COROLLA,THE VEHICLE OVERTOOK A M/CYCLE AND LOST CONTRO...,MALE,A,10,...,False,False,False,False,True,False,False,True,False,False

In [126]:
df.describe()

,cause_code,date,age_numeric,year,month,day,hour,minute
count,1090.0,1118,511.0,1118.000000,1118.000000,1118.000000,1095.0,1095.0
mean,47.59633,2017-02-11 19:12:46.368515,34.118395,2016.661896,5.983900,15.807692,14.463014,20.610046
min,1.0,2016-04-01 00:00:00,1.5,2016.000000,2.000000,1.000000,0.0,0.0
25%,19.0,2016-06-11 00:00:00,25.0,2016.000000,4.000000,9.000000,10.0,0.0
50%,37.0,2017-05-12 00:00:00,32.0,2017.000000,6.000000,16.000000,16.0,30.0
75%,76.75,2017-08-01 00:00:00,42.0,2017.000000,8.000000,22.750000,20.0,30.0
max,99.0,2017-11-06 00:00:00,90.0,2017.000000,11.000000,31.000000,23.0,56.0
std,33.340638,NaN,15.878218,0.473276,2.184775,8.499073,6.314159,16.87914

In [127]:
df.head()

,time,base_sub_base,county,road,place,vehicles_involved,accident_details,gender,age,cause_code,...,bus,lorry_truck,pickup,tractor,car_suv,unknown_vehicle,trailer_tanker,vehicle_classified,van_minivan,unspecified_vehicle
0,630,KITUI,MAKUENI,KITUI-ITHOKWE,KITUI SCHOOL,KAV 479E & KMCZ 732L SKYGO,HEAD ON COLLISION,MALE,26,7,...,False,False,False,False,False,False,False,True,False,False
1,830,VOI,TAITA TAVETA,MOMBASA-NAIROBI,IKANGA,KCC 763/ZF 0097 MAKE RENAULT TRUCK & KMDN 759R...,HEAD ON COLLISION,MALE,28,25,...,False,True,False,False,False,False,False,True,False,False
2,1330,MARIAKANI,KILIFI,MOMBASA-NAIROBI,KATOLANI,KMDK 017U HAOJIN,THE UNKNOWN M/V HIT THE MOTOR CYCLE,MALE,A & J,98,...,False,False,False,False,False,False,False,True,False,False
3,2100,ONGATA RONGAI,NAKURU,NAKURU-NAIROBI,MAASAI LODGE,KAL 900K RANGE ROVER,THE VEHICLE KNOCKED DOWN A PEDESTRIAN WHO WAS ...,MALE,65,29,...,False,False,False,False,True,False,False,True,False,False
4,1900,MATUU,MACHAKOS,MATUU-MWINGI,KIVANDINI,KAQ 865Z TOYOTA COROLLA,THE VEHICLE OVERTOOK A M/CYCLE AND LOST CONTRO...,MALE,A,10,...,False,False,False,False,True,False,False,True,False,False

In [128]:
df.columns

Index(['time', 'base_sub_base', 'county', 'road', 'place', 'vehicles_involved',
       'accident_details', 'gender', 'age', 'cause_code', 'victim_type',
       'number', 'date', 'county_raw', 'gender_raw', 'victim_type_raw',
       'age_raw', 'age_numeric', 'age_category', 'age_group', 'date_raw',
       'year', 'month', 'month_name', 'day', 'day_name', 'time_raw', 'hour',
       'minute', 'time_period', 'cause_code_raw', 'cause_group',
       'vehicles_involved_raw', 'motorcycle', 'matatu', 'bus', 'lorry_truck',
       'pickup', 'tractor', 'car_suv', 'unknown_vehicle', 'trailer_tanker',
       'vehicle_classified', 'van_minivan', 'unspecified_vehicle'],
      dtype='str')

In [129]:
df.shape

(1118, 45)

In [130]:
new_columns = [
    "age_numeric",
    "age_category",
    "age_group",
    "year",
    "month_name",
    "day_name",
    "hour",
    "time_period",
    "cause_group",
    "motorcycle",
    "car_suv",
    "lorry_truck",
    "matatu"
]

df[new_columns].head(10)

,age_numeric,age_category,age_group,year,month_name,day_name,hour,time_period,cause_group,motorcycle,car_suv,lorry_truck,matatu
0,26.0,NUMERIC AGE,25-34,2016,June,Saturday,6,MORNING,DRIVER / CYCLIST BEHAVIOUR,True,False,False,False
1,28.0,NUMERIC AGE,25-34,2016,June,Saturday,8,MORNING,DRIVER / CYCLIST BEHAVIOUR,True,False,True,False
2,<NA>,ADULT & JUVENILE,NaN,2016,June,Saturday,13,AFTERNOON,CAUSE NOT TRACED,True,False,False,False
3,65.0,NUMERIC AGE,65+,2016,June,Saturday,21,NIGHT,DRIVER / CYCLIST BEHAVIOUR,False,True,False,False
4,<NA>,ADULT,NaN,2016,June,Saturday,19,EVENING,DRIVER / CYCLIST BEHAVIOUR,False,True,False,False
5,<NA>,ADULT,NaN,2016,June,Saturday,21,NIGHT,CAUSE NOT TRACED,False,False,False,False
6,<NA>,ADULT & JUVENILE,NaN,2016,June,Saturday,12,AFTERNOON,DRIVER / CYCLIST BEHAVIOUR,False,False,True,True
7,<NA>,ADULT,NaN,2016,June,Friday,13,AFTERNOON,DRIVER / CYCLIST BEHAVIOUR,False,True,False,False
8,15.0,NUMERIC AGE,0-17,2016,June,Friday,19,EVENING,PEDESTRIAN BEHAVIOUR,False,False,True,False
9,17.0,NUMERIC AGE,0-17,2016,June,Friday,20,EVENING,DRIVER / CYCLIST BEHAVIOUR,True,False,True,False

In [131]:
df[new_columns].info()

<class 'pandas.DataFrame'>
Index: 1118 entries, 0 to 1118
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age_numeric   511 non-null    Float64
 1   age_category  1118 non-null   str
 2   age_group     511 non-null    category
 3   year          1118 non-null   int32
 4   month_name    1118 non-null   str
 5   day_name      1118 non-null   str
 6   hour          1095 non-null   Int64
 7   time_period   1118 non-null   str
 8   cause_group   1118 non-null   str
 9   motorcycle    1118 non-null   boolean
 10  car_suv       1118 non-null   boolean
 11  lorry_truck   1118 non-null   boolean
 12  matatu        1118 non-null   boolean
dtypes: Float64(1), Int64(1), boolean(4), category(1), int32(1), str(5)
memory usage: 139.9 KB

In [132]:
df[
[
"age_numeric",
"year",
"month",
"hour"
]
].describe()

       age_numeric         year        month       hour
count        511.0  1118.000000  1118.000000     1095.0
mean     34.118395  2016.661896     5.983900  14.463014
std      15.878218     0.473276     2.184775   6.314159
min            1.5  2016.000000     2.000000        0.0
25%           25.0  2016.000000     4.000000       10.0
50%           32.0  2017.000000     6.000000       16.0
75%           42.0  2017.000000     8.000000       20.0
max           90.0  2017.000000    11.000000       23.0

In [133]:
df.isnull().sum().sort_values(ascending=False)

age_group                607
age_numeric              607
cause_code                28
cause_code_raw            28
minute                    23
hour                      23
place                      6
time_raw                   5
time                       5
number                     4
county_raw                 3
road                       3
base_sub_base              2
age                        1
age_raw                    1
accident_details           1
matatu                     0
van_minivan                0
cause_group                0
vehicles_involved_raw      0
motorcycle                 0
vehicle_classified         0
bus                        0
unknown_vehicle            0
lorry_truck                0
pickup                     0
trailer_tanker             0
car_suv                    0
tractor                    0
month                      0
time_period                0
day_name                   0
day                        0
month_name                 0
year                       0
date_raw                   0
age_category               0
victim_type_raw            0
gender_raw                 0
date                       0
victim_type                0
gender                     0
vehicles_involved          0
county                     0
unspecified_vehicle        0
dtype: int64

In [134]:
df.insert(
    0,
    "accident_id",
    range(1, len(df)+1)
)

In [135]:
df.shape

(1118, 46)

In [136]:
df.to_csv(
    "road_accidents_cleaned.csv",
    index=False
)